---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          source '.github/workflows/setup.sh'
          instantfpc '.github/workflows/make.pas' build

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          pwsh -File '.github/workflows/setup.ps1'
